//! Static, license-clean gazetteer data + helpers for the rule-based NER.
//!
//! All lists are lowercased; matching is case-insensitive (ASCII fold, for
//! determinism). M1 keeps lists modest — the goal is the mechanism and
//! reasonable precision, not exhaustive coverage. Expand here (or enable the
//! opt-in CRF/POS download) for more recall. Sources are public-domain
//! (ISO country names, US Census given names) or hand-coded constants.

/// Words that join two capitalized tokens inside one entity
/// ("Bank of America", "Smith & Co", "Ludwig von Mises"). Deliberately excludes
/// "and"/"for"/"the": "and" wrongly merges separate entities ("Volkswagen and
/// BMW" is two ORGs, not one) — caught by comparison against spaCy.
pub const CONNECTORS: &[&str] = &["of", "&", "von", "van", "de", "la", "del"];

/// Honorifics that precede a PERSON. Stripped from the surface form but used as
/// a signal that the following capitalized run is an entity.
pub const TITLES: &[&str] = &[
    "mr",
    "mrs",
    "ms",
    "miss",
    "dr",
    "prof",
    "professor",
    "president",
    "sen",
    "senator",
    "rep",
    "gov",
    "governor",
    "mayor",
    "judge",
    "justice",
    "sir",
    "lord",
    "lady",
    "gen",
    "capt",
    "sgt",
    "lt",
    "col",
    "rev",
];

/// Common sentence-initial capitalized words that are NOT entities. A run that
/// begins with one of these at sentence start has it stripped; a single-token
/// run that IS one of these is rejected (kills "He"/"It"/"The" false positives).
pub const SENTENCE_STOPWORDS: &[&str] = &[
    "the",
    "a",
    "an",
    "this",
    "that",
    "these",
    "those",
    "it",
    "he",
    "she",
    "they",
    "we",
    "you",
    "i",
    "in",
    "on",
    "at",
    "as",
    "but",
    "and",
    "or",
    "for",
    "however",
    "meanwhile",
    "moreover",
    "nevertheless",
    "therefore",
    "thus",
    "when",
    "while",
    "after",
    "before",
    "if",
    "although",
    "though",
    "because",
    "since",
    "so",
    "yet",
    "still",
    "then",
    "there",
    "here",
    "now",
    "today",
    "yesterday",
    "tomorrow",
    "during",
    "despite",
    "according",
];

/// Organization suffixes → strong ORG signal.
pub const ORG_SUFFIXES: &[&str] = &[
    "inc",
    "corp",
    "co",
    "llc",
    "ltd",
    "plc",
    "lp",
    "llp",
    "company",
    "group",
    "holdings",
    "partners",
    "associates",
    "ag",
    "sa",
    "nv",
    "gmbh",
];

/// Well-known organizations — rescues sentence-initial single tokens ("Apple").
pub const ORGS: &[&str] = &[
    "apple",
    "google",
    "alphabet",
    "microsoft",
    "amazon",
    "meta",
    "facebook",
    "netflix",
    "tesla",
    "nvidia",
    "intel",
    "ibm",
    "oracle",
    "samsung",
    "sony",
    "toyota",
    "boeing",
    "walmart",
    "disney",
    "reuters",
    "bloomberg",
    "nasa",
    "fbi",
    "cia",
    "nato",
    "fda",
    "sec",
];

/// Countries (subset; public domain). GPE.
pub const COUNTRIES: &[&str] = &[
    "afghanistan",
    "argentina",
    "australia",
    "austria",
    "belgium",
    "brazil",
    "canada",
    "chile",
    "china",
    "colombia",
    "denmark",
    "egypt",
    "finland",
    "france",
    "germany",
    "greece",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "ireland",
    "israel",
    "italy",
    "japan",
    "kenya",
    "mexico",
    "netherlands",
    "nigeria",
    "norway",
    "pakistan",
    "peru",
    "poland",
    "portugal",
    "russia",
    "singapore",
    "spain",
    "sweden",
    "switzerland",
    "turkey",
    "ukraine",
    "england",
    "scotland",
    "wales",
];

/// Major cities + US states (subset; public domain). GPE/LOC.
pub const PLACES: &[&str] = &[
    "london",
    "paris",
    "berlin",
    "madrid",
    "rome",
    "tokyo",
    "beijing",
    "shanghai",
    "moscow",
    "delhi",
    "mumbai",
    "cairo",
    "lagos",
    "toronto",
    "sydney",
    "chicago",
    "boston",
    "seattle",
    "denver",
    "atlanta",
    "houston",
    "dallas",
    "miami",
    "phoenix",
    "california",
    "texas",
    "florida",
    "washington",
    "oregon",
    "nevada",
    "arizona",
    "georgia",
    "virginia",
    "ohio",
    "michigan",
    "illinois",
    "manhattan",
    "brooklyn",
];

/// Common given names (subset; US Census, public domain). Rescues single PERSON.
pub const FIRST_NAMES: &[&str] = &[
    "james",
    "john",
    "robert",
    "michael",
    "william",
    "david",
    "richard",
    "joseph",
    "thomas",
    "charles",
    "mary",
    "patricia",
    "jennifer",
    "linda",
    "elizabeth",
    "barbara",
    "susan",
    "jessica",
    "sarah",
    "karen",
    "daniel",
    "matthew",
    "anthony",
    "mark",
    "paul",
    "steven",
    "andrew",
    "george",
    "kenneth",
    "emily",
    "laura",
    "emma",
    "olivia",
    "sophia",
];

/// Case-insensitive (ASCII) membership test against a lowercased list.
#[must_use]
pub fn contains_ci(list: &[&str], word: &str) -> bool {
    let lower = word.to_ascii_lowercase();
    list.contains(&lower.as_str())
}
